--------------------------------------------------------
--  File created - Wednesday-May-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VAC_MASTER
--------------------------------------------------------

  CREATE TABLE "SYS"."VAC_MASTER" 
   (	"VACCINE_MASTER_ID" NUMBER(19,0), 
	"AGE" VARCHAR2(255 CHAR), 
	"AGEIN_DAYS" NUMBER, 
	"VACCINE_NAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.VAC_MASTER
SET DEFINE OFF;
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (1,'At Birth',0,'BCG');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (2,'At Birth',0,'Hep B');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (3,'At Birth',0,'OPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (4,'6 Weeks',42,'Hep B');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (5,'6 Weeks',42,'DTP');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (6,'6 Weeks',42,'IPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (7,'6 Weeks',42,'HIB');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (8,'6 Weeks',42,'Rota V');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (9,'6 Weeks',42,'PCV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (10,'10 Weeks',70,'PCV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (11,'10 Weeks',70,'Rota V');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (12,'10 Weeks',70,'HIB');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (13,'10 Weeks',70,'IPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (14,'10 Weeks',70,'DTP');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (15,'14 Weeks',98,'DTP');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (16,'14 Weeks',98,'IPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (17,'14 Weeks',98,'HIB');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (18,'14 Weeks',98,'Rota V');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (19,'14 Weeks',98,'PCV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (20,'6 months',181,'Hep B');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (21,'6 months',181,'OPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (22,'9 months',273,'OPV');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (23,'9 months',273,'MMR');
Insert into SYS.VAC_MASTER (VACCINE_MASTER_ID,AGE,AGEIN_DAYS,VACCINE_NAME) values (26,'12 months',365,'Hep A');
--------------------------------------------------------
--  DDL for Index SYS_C007175
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007175" ON "SYS"."VAC_MASTER" ("VACCINE_MASTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VAC_MASTER
--------------------------------------------------------

  ALTER TABLE "SYS"."VAC_MASTER" ADD PRIMARY KEY ("VACCINE_MASTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."VAC_MASTER" MODIFY ("VACCINE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VAC_MASTER" MODIFY ("AGEIN_DAYS" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VAC_MASTER" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VAC_MASTER" MODIFY ("VACCINE_MASTER_ID" NOT NULL ENABLE);
